### ISSUE TITLE
Nav bar is under the logo

### ISSUE THREAD

**Issue by laurasalisbury** [laurasalisbury/arrrgenes-treasure-tours#1]
I'd like to push my nav bar to the right of the banner but I am not sure how... usually Marbot gives me a little hint ;) 

@carolsinclair

**Comment by laurasalisbury** [comment]
@carolsinc

**Comment by carolsinc** [comment]
The class of masthead should be on your header. remove the div you have the masthead on now

**Comment by carolsinc** [comment]
<header class="masthead" role="banner">

**Comment by laurasalisbury** [comment]
OH ! Yaya, thank you
